title: Eric
description: Personal projects and stuff
url: "https://EricYC123.github.io"
# If this is a project site, set baseurl to "/repository-name".
baseurl: ""

github_username:  EricYC123

permalink: /:year/:month/:day/:title/
timezone: Australia/Sydney

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
